
CREATE TABLE "HEC_DEFINITION_GROUP" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"GROUP_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE
   )  ;

COMMENT ON COLUMN "HEC_DEFINITION_GROUP"."ID" IS 'id';
 
   COMMENT ON COLUMN "HEC_DEFINITION_GROUP"."GROUP_KEY" IS '分组key';
 
   COMMENT ON COLUMN "HEC_DEFINITION_GROUP"."GROUP_NAME" IS '分组名称';
 
   COMMENT ON COLUMN "HEC_DEFINITION_GROUP"."STATUS" IS '状态';
 
   COMMENT ON COLUMN "HEC_DEFINITION_GROUP"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "HEC_DEFINITION_GROUP"."UPDATE_TIME" IS '更新时间';