-- FINANCE_MAINT.HEC_DEFINITION_CONDITION definition

CREATE TABLE "HEC_DEFINITION_CONDITION" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(1000) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"PROCESS_DEFINITION_VERSION" VARCHAR2(100)
   ) ;