-- FINANCE_MAINT.HEC_PARAM_CONF definition

CREATE TABLE "HEC_PARAM_CONF" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_VERSION" VARCHAR2(100) NOT NULL ENABLE, 
	"PARAM_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_TASK_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"RIGHT_TYPE" VARCHAR2(100) NOT NULL ENABLE
   ) ;

COMMENT ON COLUMN "HEC_PARAM_CONF"."ID" IS 'id';
 
   COMMENT ON COLUMN "HEC_PARAM_CONF"."PROCESS_DEFINITION_ID" IS '审批流id';
 
   COMMENT ON COLUMN "HEC_PARAM_CONF"."PROCESS_DEFINITION_KEY" IS '审批流key';
 
   COMMENT ON COLUMN "HEC_PARAM_CONF"."PROCESS_DEFINITION_VERSION" IS '审批版本';
 
   COMMENT ON COLUMN "HEC_PARAM_CONF"."PARAM_KEY" IS '参数id';
 
   COMMENT ON COLUMN "HEC_PARAM_CONF"."PROCESS_DEFINITION_TASK_KEY" IS '节点id';
 
   COMMENT ON COLUMN "HEC_PARAM_CONF"."RIGHT_TYPE" IS '权限类别';