-- FINANCE_MAINT.HEC_WORKFLOW_RECEIPT_INSTANCE definition

CREATE TABLE "HEC_WORKFLOW_RECEIPT_INSTANCE" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_INSTANCE_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_ID" VARCHAR2(200), 
	"PROCESS_DEFINITION_KEY" VARCHAR2(200), 
	"RECEIPT_ID" VARCHAR2(200), 
	"RECEIPT_CODE" VARCHAR2(200), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT sysdate, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT sysdate, 
	"APPLYER" VARCHAR2(200)
   )  ;

COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."ID" IS '主键id';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."PROCESS_INSTANCE_ID" IS '流程实例id';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."PROCESS_DEFINITION_ID" IS '流程定义id';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."PROCESS_DEFINITION_KEY" IS '流程定义key';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."RECEIPT_ID" IS '单据实例id';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."RECEIPT_CODE" IS '单据类型';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."UPDATE_TIME" IS '更新时间';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_RECEIPT_INSTANCE"."APPLYER" IS '发起人';