-- FINANCE_MAINT.HEC_WORKFLOW_TASK_HISTORY definition

CREATE TABLE "HEC_WORKFLOW_TASK_HISTORY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_INSTANCE_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"RECEIPT_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0) NOT NULL ENABLE, 
	"OPINION" NUMBER(38,0) NOT NULL ENABLE, 
	"START_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"END_TIME" TIMESTAMP (6), 
	"OPERATORS" VARCHAR2(1000) NOT NULL ENABLE, 
	"TASK_DEFINITION_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(1000), 
	"TASK_ID" VARCHAR2(100) NOT NULL ENABLE
   )  ;

COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."ID" IS 'id';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."PROCESS_INSTANCE_ID" IS '流程实例ID';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."PROCESS_DEFINITION_ID" IS '流程定义ID';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."PROCESS_DEFINITION_KEY" IS '流程定义KEY';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."RECEIPT_ID" IS '单据ID';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."STATUS" IS '任务状态（0：未完成，1：完成）';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."OPINION" IS '审批意见（0：未审批，1：同意，2：拒绝）';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."START_TIME" IS '任务开始时间';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."END_TIME" IS '任务结束时间';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."OPERATORS" IS '执行人，多人用英文逗号隔开';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."TASK_DEFINITION_KEY" IS '任务节点key';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."COMMENTS" IS '批注';
 
   COMMENT ON COLUMN "HEC_WORKFLOW_TASK_HISTORY"."TASK_ID" IS '任务ID';