-- FINANCE_MAINT.HEC_DEFINITION_BASEINFO definition

CREATE TABLE "HEC_DEFINITION_BASEINFO" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"DES" VARCHAR2(3000), 
	"GROUP_KEY" VARCHAR2(200), 
	"ADMIN" VARCHAR2(200), 
	"STATUS" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE, 
	"PROCESS_DEFINITION_VERSION" VARCHAR2(100) DEFAULT '1' NOT NULL ENABLE, 
	"UPDATE_BY" VARCHAR2(200), 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"RECEIPT_CODE" VARCHAR2(200), 
	"FIT_ORG_CODES" VARCHAR2(1000)
   ) ;

COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."ID" IS 'id';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."PROCESS_DEFINITION_KEY" IS '流程定义key';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."NAME" IS '流程名称';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."DES" IS '表单说明信息';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."GROUP_KEY" IS '所在分组';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."ADMIN" IS '管理员';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."STATUS" IS '状态（1：创建，2：启用，3：挂起，4：禁用）';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."PROCESS_DEFINITION_VERSION" IS '最新版本号';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."UPDATE_BY" IS '最后更新人（工号）';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."UPDATE_TIME" IS '更新时间';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."RECEIPT_CODE" IS '单据类型';
 
   COMMENT ON COLUMN "HEC_DEFINITION_BASEINFO"."FIT_ORG_CODES" IS '适用组织架构code';