-- FINANCE_MAINT.HEC_PARAM definition

CREATE TABLE "HEC_PARAM" 
   (	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"PARAM_KEY" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_ID" VARCHAR2(200) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"PROCESS_DEFINITION_VERSION" VARCHAR2(100) NOT NULL ENABLE, 
	"PARAM_NAME" VARCHAR2(600) NOT NULL ENABLE, 
	"PARAM_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"PARAM_CANDIADATE_VALUE" VARCHAR2(100), 
	"SORT_NUMBER" NUMBER(38,0) NOT NULL ENABLE, 
	"REQUIRED" NUMBER(38,0) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE, 
	"TIP" VARCHAR2(1000) DEFAULT '请输入'
   )  ;

COMMENT ON COLUMN "HEC_PARAM"."ID" IS 'id';
 
   COMMENT ON COLUMN "HEC_PARAM"."PARAM_KEY" IS '参数key值';
 
   COMMENT ON COLUMN "HEC_PARAM"."PROCESS_DEFINITION_ID" IS '流程定义id';
 
   COMMENT ON COLUMN "HEC_PARAM"."PROCESS_DEFINITION_KEY" IS '流程key';
 
   COMMENT ON COLUMN "HEC_PARAM"."PROCESS_DEFINITION_VERSION" IS '流程版本';
 
   COMMENT ON COLUMN "HEC_PARAM"."PARAM_NAME" IS '参数名称';
 
   COMMENT ON COLUMN "HEC_PARAM"."PARAM_TYPE" IS '参数类型';
 
   COMMENT ON COLUMN "HEC_PARAM"."PARAM_CANDIADATE_VALUE" IS '候选值';
 
   COMMENT ON COLUMN "HEC_PARAM"."SORT_NUMBER" IS '序号';
 
   COMMENT ON COLUMN "HEC_PARAM"."REQUIRED" IS '是否必填';
 
   COMMENT ON COLUMN "HEC_PARAM"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "HEC_PARAM"."TIP" IS '提示信息';